name: main.yml
on:
  push:
    branches:
      - main
      
jobs:
  registration-form:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Start Vite server
      run: npm run dev &
      env:
        CI: true

    - name: Wait for Vite to be ready
      run: npx wait-on http://localhost:5173

    - name: Run Cypress tests
      run: npm run cypress:ci
      
   