name: main.yml
on:
  push:
    branches:
      - main
      
jobs:
  registration-form:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: .
          browser: chrome
          start: npm run dev
          wait-on: "http://localhost:5173"
      
   